### ISSUE TITLE
static PATH in settings.py

### ISSUE THREAD

**Issue by sbonaime** [usnistgov/NEMO#17]
Hi,

After building my own docker image, I have a problem with the PATH of the static files. 

My settings.py file is in /home/resadocker/nemo
My static dir is /home/resadocker/nemo/static

with this configuration
>STATIC_ROOT = '/home/resadocker/nemo/static/'
>STATIC_URL = '/static/'

I have the following errors
````
Not Found: /static/nemo.css
Not Found: /static/icons/preferences.png
Not Found: /static/moment.js
Not Found: /static/bootstrap/css/bootstrap.css
Not Found: /static/jquery.js
Not Found: /static/bootstrap/js/bootstrap.js
Not Found: /static/bootstrap/css/bootstrap.css
Not Found: /static/bootstrap/css/bootstrap-theme.css
Not Found: /static/typeahead.jquery.js
Not Found: /static/nemo.js
Not Found: /static/nemo.css
````

If I change to 
>STATIC_ROOT = '/home/resadocker/nemo/static/'
>STATIC_URL = '/home/resadocker/nemo/static/'

I have other errors
````
Not Found: /home/resadocker/nemo/static/typeahead.jquery.js
Not Found: /home/resadocker/nemo/static/moment.js
Not Found: /home/resadocker/nemo/static/bootstrap/css/bootstrap-theme.css
Not Found: /home/resadocker/nemo/static/nemo.css
Not Found: /home/resadocker/nemo/static/jquery.js
Not Found: /home/resadocker/nemo/static/bootstrap/js/bootstrap.js
Not Found: /home/resadocker/nemo/static/bootstrap/css/bootstrap.css
Not Found: /home/resadocker/nemo/static/nemo.js
Not Found: /home/resadocker/nemo/static/icons/preferences.png
Not Found: /home/resadocker/nemo/static/bootstrap/css/bootstrap-theme.css
Not Found: /home/resadocker/nemo/static/typeahead.jquery.js
Not Found: /home/resadocker/nemo/static/nemo.js
Not Found: /home/resadocker/nemo/static/nemo.css
````
But those files exist ! 
>ll  /home/resadocker/nemo/static/nemo.css
>-rw-r--r-- 1 root root 4.4K Feb  3 17:52 /home/resadocker/nemo/static/nemo.css

And of course, I have no graphic or colors on the main page. However, I can login !

I start the docker with or with sudo with same problem
> sudo docker run  --publish 8000:8000 --volume /home/resadocker/nemo:/nemo my_nemo

**Comment by mrampant-nist** [comment]
Hi,
in your settings.py, the `STATIC_ROOT` should be where the static files are located in the container. in your case you are mapping the folder `/home/resadocker/nemo` of your local machine into the folder `/nemo` in the container.
so you should use `STATIC_ROOT = '/nemo/'` and leave `STATIC_URL = '/static/'`

**Comment by sbonaime** [comment]
So I set like this my PATH
```
STATIC_ROOT = '/nemo/'
STATIC_URL = '/static/'

MEDIA_ROOT = '/nemo/'
MEDIA_URL = '/media/'
````
But now, here is the error :
````
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying sessions.0001_initial... OK
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 8, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 173, in handle
    if self.is_local_storage() and self.storage.location:
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 227, in is_local_storage
    return isinstance(self.storage, FileSystemStorage)
  File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 238, in inner
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 504, in _setup
    self._wrapped = get_storage_class(settings.STATICFILES_STORAGE)()
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 39, in __init__
    check_settings(base_url)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 59, in check_settings
    raise ImproperlyConfigured("The MEDIA_ROOT and STATIC_ROOT "
django.core.exceptions.ImproperlyConfigured: The MEDIA_ROOT and STATIC_ROOT settings must have different values
````
with
````
STATIC_ROOT = '/nemo/'
STATIC_URL = '/static/'

MEDIA_ROOT = '/nemo/media'
MEDIA_URL = '/media/'
````
I have other errors : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/local/lib/python3.6/site-packages/NEMO/wsgi.py", line 3, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 22, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'settings'
[2020-02-04 16:04:50 +0000] [14] [INFO] Worker exiting (pid: 14)
```

**Comment by mrampant-nist** [comment]
the second option is the right one for static and media settings

the new issue you are having seems to be unrelated to the static and media path, so I will go ahead and close this issue. maybe try again in a clean folder with just your settings.py file.
