### ISSUE TITLE
[Bug report] Pickadate not loaded when using kiosk with chromium

### ISSUE THREAD

**Issue by r-xyz** [usnistgov/NEMO#252]
The date and time picker (when creating reservations in kiosks) are not working anymore in recent versions of chromium.

## Steps to reproduce

1. Open kiosk page using Chromium
2. Select a tool, make new reservation
3. Click on date/time fields: nothing happens

## Notes
This seem to only affect datetime pickers; Keyboard and numeric input keypad work as expected in kiosks.
Everything works correctly in Firefox, but a similar warning is shown in console, too (see below).

<details>
<summary> Logs </summary>

### Chromium console logs
```
[Violation] Permissions policy violation: Synchronous requests are disabled by permissions policy. [3 times]
  send @ jquery.min.32015dd42e95.js:4
  ajax @ jquery.min.32015dd42e95.js:4
  n._evalUrl @ jquery.min.32015dd42e95.js:4
  domManip @ jquery.min.32015dd42e95.js:3
  append @ jquery.min.32015dd42e95.js:3
  (anonymous) @ jquery.min.32015dd42e95.js:3
  n.access @ jquery.min.32015dd42e95.js:2
  html @ jquery.min.32015dd42e95.js:3
  load_complete @ Cleanroom/:166
  j @ jquery.min.32015dd42e95.js:2
  fireWith @ jquery.min.32015dd42e95.js:2
  x @ jquery.min.32015dd42e95.js:4
  (anonymous) @ jquery.min.32015dd42e95.js:4
  load
  send @ jquery.min.32015dd42e95.js:4
  ajax @ jquery.min.32015dd42e95.js:4
  ajax_message @ nemo.b6574a18bcce.js:503
  ajax_post @ nemo.b6574a18bcce.js:492
  tool_report_problem @ Cleanroom/:243
  onclick @ Cleanroom/:1

Uncaught TypeError: $(...).pickadate is not a function
    at eval (eval at globalEval (jquery.min.32015dd42e95.js:2:2538), <anonymous>:5:50)
    at eval (<anonymous>)
    at Function.globalEval (jquery.min.32015dd42e95.js:2:2538)
    at n.domManip (jquery.min.32015dd42e95.js:3:17203)
    at n.append (jquery.min.32015dd42e95.js:3:14886)
    at n.<anonymous> (jquery.min.32015dd42e95.js:3:16246)
    at n.access (jquery.min.32015dd42e95.js:2:30124)
    at n.html (jquery.min.32015dd42e95.js:3:15917)
    at Object.load_complete (Cleanroom/:166:32)
    at j (jquery.min.32015dd42e95.js:2:26911)
  eval @ VM223:5
  globalEval @ jquery.min.32015dd42e95.js:2
  domManip @ jquery.min.32015dd42e95.js:3
  append @ jquery.min.32015dd42e95.js:3
  (anonymous) @ jquery.min.32015dd42e95.js:3
  n.access @ jquery.min.32015dd42e95.js:2
  html @ jquery.min.32015dd42e95.js:3
  load_complete @ Cleanroom/:166
  j @ jquery.min.32015dd42e95.js:2
  fireWith @ jquery.min.32015dd42e95.js:2
  x @ jquery.min.32015dd42e95.js:4
  (anonymous) @ jquery.min.32015dd42e95.js:4
  load
  send @ jquery.min.32015dd42e95.js:4 
  ajax @ jquery.min.32015dd42e95.js:4
  ajax_message @ nemo.b6574a18bcce.js:503
  ajax_post @ nemo.b6574a18bcce.js:492
  tool_report_problem @ Cleanroom/:243
  onclick @ Cleanroom/:1
```
###  Chromium issue log:
```
Deprecated feature used:
  Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
Affected resources:
  jquery.min.32015dd42e95.js:4
```
### Firefox Console log:
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help https://xhr.spec.whatwg.org/#sync-warning                     [jquery.min.32015dd42e95.js:4:14161](http://localhost:8000/static/jquery.min.32015dd42e95.js)
```
</details>

**Comment by r-xyz** [comment]
https://xhr.spec.whatwg.org/#sync-warning

**Comment by r-xyz** [comment]
Hi @rptmat57,
I am somehow unable to reproduce anymore on 6.1.0.dev.
Is it possible it was fixed in dev? I had a look at the commits history, but I could not find anything directly related.

**Comment by rptmat57** [comment]
Hi, I don't remember working on this.
It's possible that chromium reverted their previous change to make this a blocking error rather than a simple warning

**Comment by r-xyz** [comment]
Hi @rptmat57,

I still cannot find the root of this issue, but I double checked after updating our instance to CE 7.0.3 and it still does not work on Chromium. No pickadate shows, while other on-screen menus do (keyboard, numerical keypad).

Testing it on nemo-demo.atlantislabs.io, it works flawlessly (could not check nemo-ce-dev since it gives 500 error).
We will probably end up switching to firefox to solve it.

**Comment by r-xyz** [comment]
Great, I managed to look at it from a different angle and identified the issue! It was due to a `Permission-Policy` header containing [`sync-xhr=()`](https://udn.realityripple.com/docs/Web/HTTP/Headers/Feature-Policy/sync-xhr).
Switching it to `sync-xhr=(self)` solved the issue.
