### ISSUE TITLE
django.db.utils.OperationalError: no such column: expired

### ISSUE THREAD

**Issue by sbonaime** [usnistgov/NEMO#27]
Hi,
With the latest commit 553405b3abb318bcf3acc7281429e2f249f92ba7,
I don't have a login screen but an error 500 through nginx. 
I have the following exception in the django_error.log
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/NEMO/views/landing.py", line 21, in landing
    delete_expired_alerts()
  File "/usr/local/lib/python3.6/site-packages/NEMO/views/alerts.py", line 59, in delete_expired_alerts
    Alert.objects.filter(expiration_time__lt=timezone.now()).update(expired=True)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/query.py", line 741, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1462, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: expired
```

**Comment by mrampant-nist** [comment]
This change was actually introduced earlier in v2.1
It seems you are out of sync with the migrations, probably because migration were ran in between releases and so when it was changed again before 2.1 was final those changes were not applied for you.

here is what you can do:
1. fake back to migration before 2.1:
`python manage.py migrate --fake NEMO 0012_version_2_0_0`
2. re-apply 2.1:
`python manage.py migrate NEMO 0013_version_2_1_0`
3. fake back to now (if you have already ran the 0014_version_2_2_0 migration, otherwise you are done).
` python manage.py migrate --fake NEMO 0014_version_2_2_0`

now it's very likely you will get an error while migrating 0013_version_2_1_0 because a table was already created, if that happens, comment out the operation causing the error, which in that case it's probably this one: 
```
migrations.CreateModel(
            name='AlertCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Alert categories',
                'ordering': ['name'],
            },
        ),
```
you have to comment it out in the NEMO/migrations folder in your lib site-packages.
then rerun 2. and 3.

For that not to happen again in the future, I am strongly considering creating migration files per single change (instead of per version)

**Comment by sbonaime** [comment]
1. was done without probblem
````
 0012_version_2_0_0, from NEMO
Running migrations:
  Applying contenttypes.0001_initial... FAKED
  Applying contenttypes.0002_remove_content_type_name... FAKED
  Applying auth.0001_initial... FAKED
  Applying auth.0002_alter_permission_name_max_length... FAKED
  Applying auth.0003_alter_user_email_max_length... FAKED
  Applying auth.0004_alter_user_username_opts... FAKED
  Applying auth.0005_alter_user_last_login_null... FAKED
  Applying auth.0006_require_contenttypes_0002... FAKED
  Applying auth.0007_alter_validators_add_error_messages... FAKED
  Applying auth.0008_alter_user_username_max_length... FAKED
  Applying NEMO.0001_version_1_0_0... FAKED
  Applying NEMO.0002_version_1_1_0... FAKED
  Applying NEMO.0003_version_1_2_0... FAKED
  Applying NEMO.0004_version_1_3_0... FAKED
  Applying NEMO.0005_version_1_4_0... FAKED
  Applying NEMO.0006_version_1_8_0... FAKED
  Applying NEMO.0007_version_1_15_0... FAKED
  Applying NEMO.0008_version_1_16_0... FAKED
  Applying NEMO.0009_version_1_19_0... FAKED
  Applying NEMO.0010_version_1_20_0... FAKED
  Applying NEMO.0011_version_1_22_0... FAKED
  Applying NEMO.0012_version_2_0_0... FAKED
````
2. give me some errors 
````
python manage.py migrate NEMO 0013_version_2_1_0

Operations to perform:
  Target specific migration: 0013_version_2_1_0, from NEMO
Running migrations:
  Applying NEMO.0013_version_2_1_0...Traceback (most recent call last):
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: NEMO_tool

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_com
mand_line
    utility.execute()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwa
rds
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 112, in database_
forwards
    field,
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 327, in add_field
    self._remake_table(model, create_field=field)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 286, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: NEMO_tool
````

**Comment by sbonaime** [comment]
this is the error after at step 2)
````
 python manage.py migrate NEMO 0013_version_2_1_0
Operations to perform:
  Target specific migration: 0013_version_2_1_0, from NEMO
Running migrations:
  Applying NEMO.0013_version_2_1_0...Traceback (most recent call last):
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: NEMO_tool

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/migrations/operations/fields.py", line 112, in database_forwards
    field,
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 327, in add_field
    self._remake_table(model, create_field=field)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/schema.py", line 286, in _remake_table
    self.quote_name(model._meta.db_table),
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
    cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: NEMO_tool
````
The problem is a missing table. What can I do now ?

**Comment by mrampant-nist** [comment]
I think this is a different issue. did you install NEMO first? "pip install ./" from your folder

**Comment by sbonaime** [comment]
No I didn't...
Here is the result 
````
pip install ./
Processing /home/resadocker/NEMO
Requirement already satisfied: Django==2.2.10 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (2.2.10)
Requirement already satisfied: Pillow==7.0.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (7.0.0)
Requirement already satisfied: cryptography==2.8 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (2.8)
Requirement already satisfied: django-filter==2.2.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (2.2.0)
Requirement already satisfied: djangorestframework==3.11.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (3.11.0)
Requirement already satisfied: ldap3==2.6.1 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (2.6.1)
Requirement already satisfied: python-dateutil==2.8.1 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (2.8.1)
Requirement already satisfied: requests==2.22.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO==2.3.0) (2.22.0)
Requirement already satisfied: pytz in /home/resadocker/.local/lib/python3.7/site-packages (from Django==2.2.10->NEMO==2.3.0) (2019.3)
Requirement already satisfied: sqlparse in /home/resadocker/.local/lib/python3.7/site-packages (from Django==2.2.10->NEMO==2.3.0) (0.3.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography==2.8->NEMO==2.3.0) (1.12.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/resadocker/.local/lib/python3.7/site-packages (from cryptography==2.8->NEMO==2.3.0) (1.14.0)
Requirement already satisfied: pyasn1>=0.1.8 in /home/resadocker/.local/lib/python3.7/site-packages (from ldap3==2.6.1->NEMO==2.3.0) (0.4.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO==2.3.0) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO==2.3.0) (2.6)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO==2.3.0) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO==2.3.0) (2018.8.24)
Requirement already satisfied: pycparser in /home/resadocker/.local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.8->NEMO==2.3.0) (2.19)
Building wheels for collected packages: NEMO
  Running setup.py bdist_wheel for NEMO ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-w8jnylhr/wheels/40/f2/4e/e902881898af741d50778caf2f621dce54ba9aad9be4bedfbc
Successfully built NEMO
Installing collected packages: NEMO
  Found existing installation: NEMO 2.1.0
    Uninstalling NEMO-2.1.0:
      Successfully uninstalled NEMO-2.1.0
Successfully installed NEMO-2.3.0
````


And now, I have another error with 2)
````
✗ python manage.py migrate NEMO 0013_version_2_1_0

error loading rates
[Errno 2] No such file or directory: '/nemo/media/rates.json'
Traceback (most recent call last):
  File "/home/resadocker/.local/lib/python3.7/site-packages/NEMO/rates.py", line 52, in load_rates
    json_data = open(rates_file)
FileNotFoundError: [Errno 2] No such file or directory: '/nemo/media/rates.json'
Traceback (most recent call last):
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: NEMO_customization

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/resadocker/.local/lib/python3.7/site-packages/NEMO/urls.py", line 23, in <module>
    site_title = get_customization("site_title")
  File "/home/resadocker/.local/lib/python3.7/site-packages/NEMO/views/customization.py", line 80, in get_customization
    return Customization.objects.get(name=name).value
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: NEMO_customization
````

**Comment by mrampant-nist** [comment]
I am not able to reproduce the issue you are having.
try:
`pip uninstall NEMO`
`pip install NEMO` (this should install the last stable version of NEMO)

and try again with the migrations

**Comment by sbonaime** [comment]
same problem with 'no such table: NEMO_customization'
Maybe I can do something directly in the DB to fix the problem ? 

```
 pip uninstall NEMO                                                                                                             [290/1544]

Uninstalling NEMO-2.3.0:
  Would remove:
    /home/resadocker/.local/bin/nemo
    /home/resadocker/.local/lib/python3.7/site-packages/NEMO-2.3.0.dist-info/*
    /home/resadocker/.local/lib/python3.7/site-packages/NEMO/*
  Would not remove (might be manually added):
    /home/resadocker/.local/lib/python3.7/site-packages/NEMO/migrations/tmux-client-10170.log
Proceed (y/n)? Y
  Successfully uninstalled NEMO-2.3.0
➜  NEMO git:(master) ✗ pip install NEMO
Collecting NEMO
  Downloading https://files.pythonhosted.org/packages/e0/63/a46c15393bd165e3943ccdc422a453eb4df51dcb34b601719fcda24bff60/NEMO-2.2.3-py36-none-any.whl (891kB)
    100% |████████████████████████████████| 901kB 1.6MB/s
Requirement already satisfied: requests==2.22.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (2.22.0)
Requirement already satisfied: ldap3==2.6.1 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (2.6.1)
Requirement already satisfied: Pillow==7.0.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (7.0.0)
Requirement already satisfied: djangorestframework==3.11.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (3.11.0)
Requirement already satisfied: cryptography==2.8 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (2.8)
Requirement already satisfied: Django==2.2.10 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (2.2.10)
Requirement already satisfied: python-dateutil==2.8.1 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (2.8.1)
Requirement already satisfied: django-filter==2.2.0 in /home/resadocker/.local/lib/python3.7/site-packages (from NEMO) (2.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO) (2018.8.24)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO) (1.24.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.22.0->NEMO) (2.6)
Requirement already satisfied: pyasn1>=0.1.8 in /home/resadocker/.local/lib/python3.7/site-packages (from ldap3==2.6.1->NEMO) (0.4.8)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/resadocker/.local/lib/python3.7/site-packages (from cryptography==2.8->NEMO) (1.14.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3/dist-packages (from cryptography==2.8->NEMO) (1.12.0)
Requirement already satisfied: pytz in /home/resadocker/.local/lib/python3.7/site-packages (from Django==2.2.10->NEMO) (2019.3)
Requirement already satisfied: sqlparse in /home/resadocker/.local/lib/python3.7/site-packages (from Django==2.2.10->NEMO) (0.3.0)
Requirement already satisfied: pycparser in /home/resadocker/.local/lib/python3.7/site-packages (from cffi!=1.11.3,>=1.8->cryptography==2.8->NEMO) (2.19)
Installing collected packages: NEMO
Successfully installed NEMO-2.2.3

python manage.py migrate --fake NEMO 0012_version_2_0_0

Traceback (most recent call last):
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: NEMO_customization

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 7, in <module>
    execute_from_command_line(sys.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 361, in execute
    self.check()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 65, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
 File "/home/resadocker/.local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/resadocker/.local/lib/python3.7/site-packages/NEMO/urls.py", line 23, in <module>
    site_title = get_customization("site_title")
  File "/home/resadocker/.local/lib/python3.7/site-packages/NEMO/views/customization.py", line 80, in get_customization
    return Customization.objects.get(name=name).value
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 402, in get
    num = len(clone)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 256, in __len__
    self._fetch_all()
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1133, in execute_sql
    cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/resadocker/.local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: NEMO_customization
```

**Comment by mrampant-nist** [comment]
sorry I gave you instructions to install the earlier version with pip, but you actually have the git code.
so, in NEMO folder:
`git checkout 2.2.3`
then try the migration stuff. 

and yes you can mess with the db directly, but in this case we need to clear this "no such table" error

**Comment by sbonaime** [comment]
I did your instructions without success.... I give up this problem. 
I will start with a new fresh installation and import my data in the DB from the old DB. 
Thank you
